stages:
  - deploy

deploy_to_vercel:
  image: node:22
  stage: deploy
  script:
    - npm install -g vercel
    - vercel --token $VERCEL_TOKEN --prod
  only:
    - main  # Only deploy on commits to the main branch (adjust if needed)