[build]
command = "yarn build"
publish = "out"

[[redirects]]
from = "/e-commerce-development"
to = "https://angular.chorn.in.th/e-commerce-development"
status = 301
force = true

[[redirects]]
from = "/mvp"
to = "https://angular.chorn.in.th/mvp"
status = 301
force = true

[[redirects]]
from = "/back-end-development"
to = "/services/fullstack-development/"
status = 301
force = true

[[redirects]]
from = "/contact"
to = "/contact-chorn"
status = 301
force = true

[[redirects]]
from = "/front-end-development"
to = "/outsourcing-software-development/front-end-developer/"
status = 301
force = true

[[redirects]]
from = "/custom-software-development"
to = "/services/web-development/"
status = 301
force = true

[[redirects]]
from = "/devops-and-testing"
to = "/services/devops-testing/"
status = 301
force = true

[[redirects]]
from = "/about-us/2"
to = "/about-chorn"
status = 301
force = true

[[redirects]]
from = "/single-page-application"
to = "/outsourcing-software-development/front-end-developer/"
status = 301
force = true

[[redirects]]
from = "/galleries"
to = "/404"
status = 301
force = true

[[redirects]]
from = "/gits"
to = "https://github.com/chorn-hub"
status = 301
force = true

[[redirects]]
from = "/microservices-technology"
to = "https://angular.chorn.in.th/microservices-technology"
status = 301
force = true

[[redirects]]
from = "/responsive-web-design"
to = "https://angular.chorn.in.th/responsive-web-design"
status = 301
force = true

[[redirects]]
from = "/scaling"
to = "https://angular.chorn.in.th/scaling"
status = 301
force = true

[[redirects]]
from = "/services/frontend-development"
to = "/outsourcing-software-development/front-end-developer/"
status = 301
force = true

[[redirects]]
from = "/services/full-stack-developer"
to = "/outsourcing-software-development/full-stack-developer/"
status = 301
force = true

[[redirects]]
from = "/services/fullstack-development/"
to = "/outsourcing-software-development/full-stack-developer/"
status = 301
force = true

[[redirects]]
from = "/services/frontend-development/next.js/"
to = "/outsourcing-software-development/front-end-developer/nextjs-developer/"
status = 301
force = true

[[redirects]]
from = "/services/frontend-development/react/"
to = "/outsourcing-software-development/front-end-developer/react-developer/"
status = 301
force = true

[[redirects]]
from = "/services/frontend-development/angular/"
to = "/outsourcing-software-development/front-end-developer/angular-developer/"
status = 301
force = true

[[redirects]]
from = "/services/frontend-development/vue/"
to = "/outsourcing-software-development/front-end-developer/vue-developer/"
status = 301
force = true

[[redirects]]
from = "/services/fullstack-development/nodejs/"
to = "/outsourcing-software-development/full-stack-developer/nodejs-developer/"
status = 301
force = true

[[redirects]]
from = "/services/fullstack-development/java-spring-boot/"
to = "/outsourcing-software-development/full-stack-developer/java-spring-boot-developer/"
status = 301
force = true

[[redirects]]
from = "/services/fullstack-development/dotnetcore/"
to = "/outsourcing-software-development/full-stack-developer/dotnetcore-developer/"
status = 301
force = true

[[redirects]]
from = "/services/fullstack-development/php/"
to = "/outsourcing-software-development/full-stack-developer/php-developer/"
status = 301
force = true

[[redirects]]
from = "/services/fullstack-development/python/"
to = "/outsourcing-software-development/full-stack-developer/python-developer/"
status = 301
force = true

[[redirects]]
from = "/services/fullstack-development/go-lang/"
to = "/outsourcing-software-development/full-stack-developer/go-developer/"
status = 301
force = true

[[redirects]]
from = "/services/fullstack-development/typescript/"
to = "/outsourcing-software-development/full-stack-developer/typescript-javascript-developer/"
status = 301
force = true

[[redirects]]
from = "/src"
to = "/"
status = 301
force = true

[[redirects]]
from = "/*"
to = "index.html"
status = 200