[build]
command = "yarn build"
publish = "out"

# Redirect www to non-www (Important for canonicalization)
[[redirects]]
from = "https://www.chorn.in.th/*"
to = "https://chorn.in.th/:splat"  # :splat preserves the path
status = 301
force = true # Ensure this redirect always happens

# Redirect angular subdomain to main domain
[[redirects]]
from = "https://angular.chorn.in.th/*"
to = "https://chorn.in.th/:splat"  # Redirect to the root of your main domain
status = 301
force = true

# Redirect outsourcing-software-development/full-stack-developer
[[redirects]]
from = "https://chorn.in.th/outsourcing-software-development/full-stack-developer/*"
to = "https://chorn.in.th/services/full-stack-developer/:splat"
status = 301
force = true

# Redirect services/front-end-developer (No change needed, but good to confirm)
[[redirects]]
from = "https://chorn.in.th/outsourcing-software-development/front-end-developer/*"
to = "https://chorn.in.th/services/front-end-developer/:splat" # This effectively canonicalizes the URL
status = 301
force = true

# Existing redirects (Review these carefully)
[[redirects]]
from = "/e-commerce-development"
to = "/services/web-development/" # Redirect to your internal path
status = 301 # Use 301 for permanent redirects
force = true

[[redirects]]
from = "/mvp"
to = "/services/web-development/"
status = 301
force = true

[[redirects]]
from = "/back-end-development"
to = "/services/full-stack-developer/"
status = 301
force = true

[[redirects]]
from = "/contact"
to = "/contact-chorn"
status = 301
force = true

[[redirects]]
from = "/front-end-development"
to = "/services/front-end-developer/"
status = 301
force = true

[[redirects]]
from = "/full-stack-development"
to = "/services/full-stack-developer/"
status = 301
force = true

[[redirects]]
from = "/custom-software-development"
to = "/services/web-development/"
status = 301
force = true

[[redirects]]
from = "/devops-and-testing"
to = "/services/devops-testing/"
status = 301
force = true

[[redirects]]
from = "/about-us/2"
to = "/about-chorn"
status = 301
force = true

[[redirects]]
from = "/single-page-application"
to = "/services/web-development/"
status = 301
force = true

[[redirects]]
from = "/galleries"
to = "/gallery/"
status = 301
force = true

[[redirects]]
from = "/gits"
to = "/services/devops-testing/github/"
status = 301
force = true

[[redirects]]
from = "/microservices-technology"
to = "/services/web-development/"
status = 301
force = true

[[redirects]]
from = "/responsive-web-design"
to = "/services/web-development/"
status = 301
force = true

[[redirects]]
from = "/scaling"
to = "/services/web-development/"
status = 301
force = true

[[redirects]]
from = "/chorn-services"
to = "/services/web-development/"
status = 301
force = true

[[redirects]]
from = "/services"
to = "/services/web-development/"
status = 301
force = true

[[redirects]]
from = "/src"
to = "/"
status = 301
force = true

# Catch-all redirect (Important for Next.js routing)
[[redirects]]
from = "/*"
to = "/index.html" # Or your main entry point if different
status = 200 # Or 404 if you want to handle routing client-side